name: Question
description: Ask a general question about TRACE
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Check the [FAQ](../../docs/faq.md) first. Your question might already be answered
        there.

  - type: textarea
    id: question
    attributes:
      label: Your question
    validations:
      required: true
